### ISSUE TITLE
WIzard spell "Form of the helpless beast" cannot be casted

### ISSUE THREAD

**Issue by Zeeero** [GregRos/IEMod.pw#80]
the aforementioned 6th level wizard spell  "Form of the helpless beast" cannot be casted on targets that should be applicable. the spell was added in white march 2

**Comment by tjayharvey** [comment]
Is this fixed in the new version? It looks like someone adjusted the targeting code and should have compensated.

**Comment by Zeeero** [comment]
i just tested version 5.2.1 from the nexus and the spell still cannot be cast. thanks for looking into this btw :+1:
